import inspect
import pickle
import warnings
from pathlib import Path

import flax.linen as nn
import flax.serialization

# Author: Harshdeep Sharma
# JAX/Flax port: minimal changes from base_model.py

class BaseModel(nn.Module):
    """Based class for all Models

    This class has two main functionalities:
    * It monitors the creation of subclass, that are automatically registered
      for users to use by name using the library's config system
    * When a new instance of this class is created, the init call is intercepted
      so we can store the parameters used to create the instance.
      This makes it possible to save trained models along with their init parameters,
      and therefore load saved models easily.

    Notes
    -----
    Model can be versioned using the _version class attribute.
    This can be used for sanity check when loading models from checkpoints to verify the
    model hasn't been updated since.
    """

    _models = dict()
    _version = "0.1.0"

    def __init_subclass__(cls, name=None, **kwargs):
        """When a subclass is created, register it in _models
        We look for an existing name attribute.
        If not give, then we use the class' name.
        """
        super().__init_subclass__(**kwargs)
        if name is not None:
            BaseModel._models[name.lower()] = cls
            cls._name = name
        else:
            BaseModel._models[cls.__name__.lower()] = cls
            cls._name = cls.__name__

    def __new__(cls, *args, **kwargs):
        """Verify arguments and save init kwargs for loading/saving

        We inspect the class' signature and check for unused parameters, or
        parameters not passed.

        We store all the args and kwargs given so we can duplicate the instance transparently.
        """
        sig = inspect.signature(cls)
        model_name = cls.__name__

        verbose = kwargs.get("verbose", False)
        for key in kwargs:
            if key not in sig.parameters:
                if verbose:
                    print(
                        f"Given argument key={key} "
                        f"that is not in {model_name}'s signature."
                    )

        for key, value in sig.parameters.items():
            if (value.default is not inspect._empty) and (key not in kwargs):
                if verbose:
                    print(
                        f"Keyword argument {key} not specified for model {model_name}, "
                        f"using default={value.default}."
                    )
                kwargs[key] = value.default

        if hasattr(cls, "_version"):
            kwargs["_version"] = cls._version
        kwargs["args"] = args
        kwargs["_name"] = cls._name
        instance = super().__new__(cls)
        instance._init_kwargs = kwargs

        return instance

    def get_state_dict(self, params: dict) -> dict:
        """Returns a state dict containing model params and version metadata.

        Parameters
        ----------
        params : dict
            Flax parameter dict obtained from model.init(...)

        Returns
        -------
        dict
            state dict with params bytes and metadata
        """
        state_dict = {
            "params_bytes": flax.serialization.to_bytes(params),
            "_metadata": self._init_kwargs,
        }
        return state_dict

    def load_state_dict(self, params_target: dict, state_dict: dict) -> dict:
        """Loads params from a state dict, with version checking.

        Parameters
        ----------
        params_target : dict
            A reference param structure (e.g. from model.init) used to restore shape info
        state_dict : dict
            state dictionary generated by ``get_state_dict``

        Returns
        -------
        dict
            restored Flax parameter dict
        """
        metadata = state_dict.get("_metadata", None)

        if metadata is not None:
            saved_version = metadata.get("_version", None)
            if saved_version is None:
                warnings.warn(f"Saved instance of {self.__class__} has no stored version attribute.")
            if saved_version != self._version:
                warnings.warn(
                    f"Attempting to load a {self.__class__} of version {saved_version}, "
                    f"but current version of {self.__class__} is {self._version}"
                )

        return flax.serialization.from_bytes(params_target, state_dict["params_bytes"])

    def save_checkpoint(self, save_folder, save_name, params: dict):
        """Saves the model params and init kwargs under the given folder and name.

        Parameters
        ----------
        save_folder : str or Path
        save_name : str
        params : dict
            Flax parameter dict obtained from model.init(...)
        """
        save_folder = Path(save_folder)
        if not save_folder.exists():
            save_folder.mkdir(parents=True)

        params_filepath = save_folder / f"{save_name}_params.bytes"
        params_filepath.write_bytes(flax.serialization.to_bytes(params))

        metadata_filepath = save_folder / f"{save_name}_metadata.pkl"
        with open(metadata_filepath, "wb") as f:
            pickle.dump(self._init_kwargs, f)

    def load_checkpoint(self, save_folder, save_name, params_target: dict) -> dict:
        """Loads and returns the model params from a checkpoint.

        Parameters
        ----------
        save_folder : str or Path
        save_name : str
        params_target : dict
            A reference param structure used by flax.serialization.from_bytes

        Returns
        -------
        dict
            restored Flax parameter dict
        """
        save_folder = Path(save_folder)
        params_filepath = save_folder / f"{save_name}_params.bytes"
        return flax.serialization.from_bytes(params_target, params_filepath.read_bytes())

    @classmethod
    def from_checkpoint(cls, save_folder, save_name, params_target: dict):
        """Instantiates the model from a checkpoint and returns (instance, params).

        Parameters
        ----------
        save_folder : str or Path
        save_name : str
        params_target : dict
            A reference param structure used by flax.serialization.from_bytes

        Returns
        -------
        tuple[BaseModel, dict]
            (model instance, restored params dict)
        """
        save_folder = Path(save_folder)

        metadata_filepath = save_folder / f"{save_name}_metadata.pkl"
        with open(metadata_filepath, "rb") as f:
            init_kwargs = pickle.load(f)

        version = init_kwargs.pop("_version", None)
        if hasattr(cls, "_version") and version != cls._version:
            warnings.warn(
                f"Checkpoint saved for version {version} of model {cls._name} "
                f"but current code is version {cls._version}"
            )

        init_kwargs.pop("_name", None)

        if "args" in init_kwargs:
            init_args = init_kwargs.pop("args")
        else:
            init_args = []

        instance = cls(*init_args, **init_kwargs)
        params = instance.load_checkpoint(save_folder, save_name, params_target)
        return instance, params


def available_models():
    """List the available neural operators"""
    return list(BaseModel._models.keys())


def get_model_jax(config):
    """Returns an instantiated model for the given config

    * Reads the model to be used from config['arch']
    * Adjusts config["arch"]["data_channels"] accordingly if multi-grid patching is used

    Parameters
    ----------
    config : Bunch or dict-like
        configuration, must have
        arch = config['arch'] (string)
        and the corresponding config[arch] (a subdict with the kwargs of the model)

    Returns
    -------
    model : nn.Module
        the instantiated module
    """
    arch = config.model["model_arch"].lower()
    model_config = config.model.copy()

    model_config.pop("model_arch", None)

    data_channels = model_config.pop("data_channels")
    try:
        patching_levels = config["patching"]["levels"]
    except KeyError:
        patching_levels = 0
    if patching_levels:
        data_channels *= patching_levels + 1
    model_config["in_channels"] = data_channels

    try:
        return BaseModel._models[arch](**model_config)
    except KeyError:
        raise ValueError(f"Got config.arch={arch}, expected one of {available_models()}.")
